Support for Modifying instances state
YaleSpinup/ec2-api pull request #25
Opened 2022-04-27 15:29 UTC by nvnyale

2022-04-27 15:59 UTC, tenyo requested changes

2022-04-27 15:59 UTC, tenyo commented on api/types.go
> +type Ec2ChangeInstanceStateInput struct {
`Ec2InstanceStateChangeRequest`

2022-04-28 15:11 UTC, nvnyale commented on api/types.go
> +type Ec2ChangeInstanceStateInput struct {
Renamed.

2022-04-28 15:11 UTC, nvnyale commented on ec2/instances.go
> +func (e *Ec2) ChangeInstancesState(ctx context.Context, state string, ids ...string) error {
Done.

2022-04-28 18:39 UTC, tenyo approved these changes
Looks great 👍

2022-04-28 20:27 UTC, merged