Tags for volumes in an Instance
YaleSpinup/ec2-api pull request #35
Opened 2022-06-13 19:53 UTC by nvnyale

2022-06-14 02:13 UTC, tenyo requested changes

2022-06-14 02:13 UTC, tenyo commented on ec2/tags.go
> +	describeVolumesInput := ec2.DescribeVolumesInput{
I don't think all this logic belongs here - should probably move to an orchestrator function.

2022-06-14 02:13 UTC, tenyo commented on ec2/tags.go
> +	describeVolumesInput := ec2.DescribeVolumesInput{
We already have a `ListInstanceVolumes` function that does this, so why not just call that?

2022-06-15 20:54 UTC, tenyo reviewed
Excellent, this is much better! Let's confirm that it works as expected and we can merge it

2022-06-16 14:24 UTC, nvnyale commented on ec2/tags.go
> +func (e *Ec2) UpdateInstanceTags(ctx context.Context, input *ec2.CreateTagsInput) error {
Renamed.

2022-06-16 16:01 UTC, tenyo approved these changes

2022-06-16 21:32 UTC, merged