Route conversion for the List and Get routes for security groups
YaleSpinup/ec2-api pull request #9
Opened 2021-09-09 16:34 UTC by btassone

Removes the old ProxyRequestHandler calls to the ruby api on security groups for the list and get routes. These routes have been updated to use functions inside the go api instead.

**handlers_security.go**
* Added SecurityGroupListHandler function.
* Added SecurityGroupGetHandler function.

**routes.go**
* Removed reference to the ProxyRequestHandler function for the security groups List route and replaced it with the SecurityGroupListHandler function.
* Removed reference to the ProxyRequestHandler function for the security groups Get route and replace it with the SecurityGroupGetHandler function.

**security.go**
* Added ListSecurityGroups function
* Added the GetSecurityGroup function

**types.go**
* Added toEc2SecurityGroupResponse function
* Added toEc2SecurityGroupIpPermissions function
* Added Ec2SecurityGroupResponse type
* Added Ec2SecurityGroupIpPermission type
* Added Ec2SecurityGroupIpRange type
* Added Ec2SecurityGroupIpv6Range type
* Added Ec2SecurityGroupPrefixListId type
* Added Ec2SecurityGroupUserIdGroupPair type

2021-09-09 17:57 UTC, fishnix requested changes
Looks good!  Nice work, just a few minor things.

I also see some differences, especially around empty values.  You can probably implement custom MarshalJSON  functions for those types (you can see an example for `Ec2ImageVolumeMap` in the same file.

```
➜  tmp jd  -set rb.json go.json
@ ["incoming_rules",["set"],{}]
- {"ip_protocol":"-1","ip_ranges":[],"ipv_6_ranges":[],"prefix_list_ids":[],"user_id_group_pairs":[{"description":"All servers in this space can talk to each other","group_id":"sg-abcdefghijklmo","user_id":"xxxxxxxxxxxx"}]}
+ {"from_port":0,"ip_protocol":"-1","ip_ranges":[],"ipv_6_ranges":[],"prefix_list_ids":[],"to_port":0,"user_id_group_pairs":[{"description":"All servers in this space can talk to each other","group_id":"sg-abcdefghijklmo","group_name":"","peering_status":"","user_id":"xxxxxxxxxxxx","vpc_id":"","vpc_peering_connection":""}]}
@ ["outgoing_rules",["set"],{}]
- {"ip_protocol":"-1","ip_ranges":[{"cidr_ip":"0.0.0.0/0"}],"ipv_6_ranges":[],"prefix_list_ids":[],"user_id_group_pairs":[]}
+ {"from_port":0,"ip_protocol":"-1","ip_ranges":[{"cidr_ip":"0.0.0.0/0","description":""}],"ipv_6_ranges":[],"prefix_list_ids":[],"to_port":0,"user_id_group_pairs":[]}
@ ["tags"]
- []
+ null
@ ["owner_id"]
+ "xxxxxxxxxxxx"
```

2021-09-09 17:57 UTC, fishnix commented on .gitignore
> +.idea/
👀 newline

2021-09-09 17:57 UTC, fishnix commented on api/handlers_security.go
> +package api
not a big deal, but let's name the file `handlers_security_groups.go` or `handlers_sgs.go`

2021-09-09 17:57 UTC, fishnix commented on ec2/security.go
> +		GroupIds: aws.StringSlice([]string{}),
✂️ you dont need this field

2021-09-09 17:57 UTC, fishnix commented on ec2/security.go
> +	log.Debugf("returning list of %d snapshots", len(out.SecurityGroups))
`security groups`

2021-09-09 17:57 UTC, fishnix commented on ec2/security.go
> +		}
I would suggest a couple of things here:
- set the default value for `sgName` first and then just override it
- don't bother with the `tags` variable, its unecessary
- use the aws sdk helper utilities
- break out of the loop once you find the Name tag

something like this:

```golang
	for i, s := range out.SecurityGroups {
		sgName := s.GroupName
		for _, t := range s.Tags {
			if aws.StringValue(t.Key) == "Name" {
				sgName = t.Value
				break
			}
		}

		list[i] = map[string]*string{
			aws.StringValue(s.GroupId): sgName,
		}
	}
```

2021-09-10 19:41 UTC, tenyo approved these changes
Looks very good 👍 Just the one comment

2021-09-10 19:41 UTC, tenyo commented on ec2/sgs.go
> +	input := ec2.DescribeSecurityGroupsInput{
I don't think you need this `input` variable here, it can just go inline with the call below

2021-09-10 19:41 UTC, tenyo commented on ec2/sgs.go
> +	input := ec2.DescribeSecurityGroupsInput{
same here

2021-09-10 22:17 UTC, fishnix commented
This looks good - lets cut a pre-release and deploy it to test.  It should "just work"

2021-09-12 11:41 UTC, fishnix approved these changes
looks good 👍

2021-09-12 15:00 UTC, merged